# -*- coding: utf-8 -*-
"""Verified model-specific presets for the simulated HONU-MRAC workflow."""

MODEL_RECOMMENDED_PRESETS = {'quadrotor_roll': {'dt_sim': 0.002,
                    'dt': 0.02,
                    't_end': 30.0,
                    'step_hold_sec': 0.5,
                    'reference_step_hold_sec': 0.5,
                    'tau_u': 0.1,
                    'plant_n_y': 5,
                    'plant_n_u': 5,
                    'preg_blackbox_enabled': False,
                    'r_preg': 1.0,
                    'Tau_1': 1.0,
                    'Tau_2': 1.0,
                    'tau_d': 0.1,
                    'plant_training_method': 'batch',
                    'plant_batch_r_0': 0.0001,
                    'plant_qnu_batch_r_0': 0.01,
                    'ctrl_learning': 'NGD',
                    'ctrl_epochs': 5,
                    'mu_v': 0.01,
                    'mu_r_0': 0.001,
                    'ctrl_qnu_learning': 'NGD',
                    'ctrl_qnu_epochs': 5,
                    'mu_v_qnu': 0.02,
                    'mu_r_0_qnu': 0.0005},
 'quadrotor_altitude': {'dt_sim': 0.005,
                        'dt': 0.05,
                        't_end': 60.0,
                        'step_hold_sec': 1.5,
                        'reference_step_hold_sec': 1.5,
                        'tau_u': 0.25,
                        'plant_n_y': 5,
                        'plant_n_u': 5,
                        'preg_blackbox_enabled': False,
                        'r_preg': 1.0,
                        'Tau_1': 1.0,
                        'Tau_2': 1.0,
                        'tau_d': 0.25,
                        'plant_training_method': 'batch',
                        'plant_batch_r_0': 0.0001,
                        'plant_qnu_batch_r_0': 0.01,
                        'ctrl_learning': 'NGD',
                        'ctrl_epochs': 5,
                        'mu_v': 0.01,
                        'mu_r_0': 0.001,
                        'ctrl_qnu_learning': 'NGD',
                        'ctrl_qnu_epochs': 5,
                        'mu_v_qnu': 0.02,
                        'mu_r_0_qnu': 0.0005},
 'two_mass_actuator_grounded_m2_linear_viscous': {'dt_sim': 0.002,
                                                  'dt': 0.02,
                                                  't_end': 20.0,
                                                  'step_hold_sec': 0.5,
                                                  'reference_step_hold_sec': 0.5,
                                                  'tau_u': 0.1,
                                                  'plant_n_y': 5,
                                                  'plant_n_u': 5,
                                                  'preg_blackbox_enabled': False,
                                                  'r_preg': 1.0,
                                                  'Tau_1': 1.0,
                                                  'Tau_2': 1.0,
                                                  'tau_d': 0.1,
                                                  'plant_training_method': 'batch',
                                                  'plant_batch_r_0': 0.0001,
                                                  'plant_qnu_batch_r_0': 0.01,
                                                  'ctrl_learning': 'NGD',
                                                  'ctrl_epochs': 5,
                                                  'mu_v': 0.01,
                                                  'mu_r_0': 0.001,
                                                  'ctrl_qnu_learning': 'NGD',
                                                  'ctrl_qnu_epochs': 5,
                                                  'mu_v_qnu': 0.02,
                                                  'mu_r_0_qnu': 0.0005},
 'two_mass_actuator_grounded_m2_lugre': {'dt_sim': 0.001,
                                         'dt': 0.02,
                                         't_end': 24.0,
                                         'step_hold_sec': 0.8,
                                         'reference_step_hold_sec': 0.8,
                                         'tau_u': 0.1,
                                         'plant_n_y': 5,
                                         'plant_n_u': 5,
                                         'preg_blackbox_enabled': False,
                                         'r_preg': 1.0,
                                         'Tau_1': 1.0,
                                         'Tau_2': 1.0,
                                         'tau_d': 0.1,
                                         'plant_training_method': 'batch',
                                         'plant_batch_r_0': 0.0001,
                                         'plant_qnu_batch_r_0': 0.01,
                                         'ctrl_learning': 'NGD',
                                         'ctrl_epochs': 5,
                                         'mu_v': 0.01,
                                         'mu_r_0': 0.001,
                                         'ctrl_qnu_learning': 'NGD',
                                         'ctrl_qnu_epochs': 5,
                                         'mu_v_qnu': 0.02,
                                         'mu_r_0_qnu': 0.0005},
 'bioreactor_dissolved_oxygen': {'dt_sim': 0.05,
                                 'dt': 0.5,
                                 't_end': 200.0,
                                 'step_hold_sec': 5.0,
                                 'reference_step_hold_sec': 5.0,
                                 'tau_u': 2.5,
                                 'plant_n_y': 5,
                                 'plant_n_u': 5,
                                 'preg_blackbox_enabled': False,
                                 'r_preg': 1.0,
                                 'Tau_1': 1.0,
                                 'Tau_2': 1.0,
                                 'tau_d': 2.5,
                                 'plant_training_method': 'batch',
                                 'plant_batch_r_0': 0.0001,
                                 'plant_qnu_batch_r_0': 0.01,
                                 'ctrl_learning': 'NGD',
                                 'ctrl_epochs': 5,
                                 'mu_v': 0.01,
                                 'mu_r_0': 0.001,
                                 'ctrl_qnu_learning': 'NGD',
                                 'ctrl_qnu_epochs': 5,
                                 'mu_v_qnu': 0.02,
                                 'mu_r_0_qnu': 0.0005},
 'photobioreactor_ph_co2': {'dt_sim': 0.1,
                            'dt': 1.0,
                            't_end': 300.0,
                            'step_hold_sec': 10.0,
                            'reference_step_hold_sec': 10.0,
                            'tau_u': 5.0,
                            'plant_n_y': 5,
                            'plant_n_u': 5,
                            'preg_blackbox_enabled': False,
                            'r_preg': 1.0,
                            'Tau_1': 1.0,
                            'Tau_2': 1.0,
                            'tau_d': 5.0,
                            'plant_training_method': 'batch',
                            'plant_batch_r_0': 0.0001,
                            'plant_qnu_batch_r_0': 0.01,
                            'ctrl_learning': 'NGD',
                            'ctrl_epochs': 5,
                            'mu_v': 0.01,
                            'mu_r_0': 0.001,
                            'ctrl_qnu_learning': 'NGD',
                            'ctrl_qnu_epochs': 5,
                            'mu_v_qnu': 0.02,
                            'mu_r_0_qnu': 0.0005},
 'chemostat_monod_biomass': {'dt_sim': 0.2,
                             'dt': 2.0,
                             't_end': 600.0,
                             'step_hold_sec': 20.0,
                             'reference_step_hold_sec': 20.0,
                             'tau_u': 10.0,
                             'plant_n_y': 5,
                             'plant_n_u': 5,
                             'preg_blackbox_enabled': True,
                             'r_preg': -0.25,
                             'Tau_1': 5.0,
                             'Tau_2': 10.0,
                             'tau_d': 10.0,
                             'plant_training_method': 'batch',
                             'plant_batch_r_0': 0.0001,
                             'plant_qnu_batch_r_0': 0.1,
                             'ctrl_learning': 'NGD',
                             'ctrl_epochs': 5,
                             'mu_v': 0.003,
                             'mu_r_0': 0.0002,
                             'ctrl_qnu_learning': 'NGD',
                             'ctrl_qnu_epochs': 5,
                             'mu_v_qnu': 0.003,
                             'mu_r_0_qnu': 0.0001},
 'drug_infusion_pk': {'dt_sim': 0.05,
                      'dt': 0.5,
                      't_end': 300.0,
                      'step_hold_sec': 10.0,
                      'reference_step_hold_sec': 10.0,
                      'tau_u': 2.5,
                      'plant_n_y': 5,
                      'plant_n_u': 5,
                      'preg_blackbox_enabled': True,
                      'r_preg': 0.5,
                      'Tau_1': 2.0,
                      'Tau_2': 3.0,
                      'tau_d': 2.5,
                      'plant_training_method': 'batch',
                      'plant_batch_r_0': 0.0001,
                      'plant_qnu_batch_r_0': 100.0,
                      'ctrl_learning': 'NGD',
                      'ctrl_epochs': 5,
                      'mu_v': 0.003,
                      'mu_r_0': 0.0002,
                      'ctrl_qnu_learning': 'NGD',
                      'ctrl_qnu_epochs': 5,
                      'mu_v_qnu': 0.003,
                      'mu_r_0_qnu': 0.0001},
 'drug_infusion_pkpd': {'dt_sim': 0.1,
                        'dt': 1.0,
                        't_end': 500.0,
                        'step_hold_sec': 20.0,
                        'reference_step_hold_sec': 20.0,
                        'tau_u': 5.0,
                        'plant_n_y': 5,
                        'plant_n_u': 5,
                        'preg_blackbox_enabled': True,
                        'r_preg': 0.5,
                        'Tau_1': 5.0,
                        'Tau_2': 8.0,
                        'tau_d': 5.0,
                        'plant_training_method': 'batch',
                        'plant_batch_r_0': 0.0001,
                        'plant_qnu_batch_r_0': 10.0,
                        'ctrl_learning': 'NGD',
                        'ctrl_epochs': 5,
                        'mu_v': 0.003,
                        'mu_r_0': 0.0002,
                        'ctrl_qnu_learning': 'NGD',
                        'ctrl_qnu_epochs': 5,
                        'mu_v_qnu': 0.003,
                        'mu_r_0_qnu': 0.0001},
 'glucose_insulin_bergman': {'dt_sim': 0.2,
                             'dt': 2.0,
                             't_end': 800.0,
                             'step_hold_sec': 20.0,
                             'reference_step_hold_sec': 20.0,
                             'tau_u': 10.0,
                             'plant_n_y': 5,
                             'plant_n_u': 5,
                             'preg_blackbox_enabled': True,
                             'r_preg': -0.05,
                             'Tau_1': 10.0,
                             'Tau_2': 20.0,
                             'tau_d': 10.0,
                             'plant_training_method': 'batch',
                             'plant_batch_r_0': 0.0001,
                             'plant_qnu_batch_r_0': 1000.0,
                             'ctrl_learning': 'NGD',
                             'ctrl_epochs': 5,
                             'mu_v': 0.003,
                             'mu_r_0': 0.0002,
                             'ctrl_qnu_learning': 'NGD',
                             'ctrl_qnu_epochs': 5,
                             'mu_v_qnu': 0.003,
                             'mu_r_0_qnu': 0.0001},
 'peltier_thermal_asymmetric': {'dt_sim': 0.01,
                                'dt': 0.1,
                                't_end': 160.0,
                                'step_hold_sec': 5.0,
                                'reference_step_hold_sec': 8.0,
                                'tau_u': 0.2,
                                'plant_n_y': 7,
                                'plant_n_u': 7,
                                'preg_blackbox_enabled': False,
                                'r_preg': 1.0,
                                'Tau_1': 1.0,
                                'Tau_2': 2.0,
                                'tau_d': 0.2,
                                'plant_training_method': 'batch',
                                'plant_batch_r_0': 0.0001,
                                'plant_qnu_batch_r_0': 0.01,
                                'ctrl_learning': 'NGD',
                                'ctrl_epochs': 8,
                                'mu_v': 0.005,
                                'mu_r_0': 0.0005,
                                'ctrl_qnu_learning': 'NGD',
                                'ctrl_qnu_epochs': 8,
                                'mu_v_qnu': 0.005,
                                'mu_r_0_qnu': 0.0002},
 'bidirectional_tank_level': {'dt_sim': 0.01,
                              'dt': 0.1,
                              't_end': 120.0,
                              'step_hold_sec': 4.0,
                              'reference_step_hold_sec': 6.0,
                              'tau_u': 0.2,
                              'plant_n_y': 6,
                              'plant_n_u': 6,
                              'preg_blackbox_enabled': False,
                              'r_preg': 1.0,
                              'Tau_1': 1.0,
                              'Tau_2': 1.5,
                              'tau_d': 0.2,
                              'plant_training_method': 'batch',
                              'plant_batch_r_0': 0.0001,
                              'plant_qnu_batch_r_0': 0.01,
                              'ctrl_learning': 'NGD',
                              'ctrl_epochs': 8,
                              'mu_v': 0.005,
                              'mu_r_0': 0.0005,
                              'ctrl_qnu_learning': 'NGD',
                              'ctrl_qnu_epochs': 8,
                              'mu_v_qnu': 0.005,
                              'mu_r_0_qnu': 0.0002}}


# Stronger-friction LuGre 2 starts from the same sampling and learning preset.
MODEL_RECOMMENDED_PRESETS["two_mass_actuator_grounded_m2_lugre2"] = dict(
    MODEL_RECOMMENDED_PRESETS["two_mass_actuator_grounded_m2_lugre"]
)


# Presets for additional cross-domain SISO ODE models.
def _cross_domain_preset(dt_sim, dt, t_end, hold, tau_u, n=6):
    return {
        "dt_sim": dt_sim, "dt": dt, "t_end": t_end,
        "step_hold_sec": hold, "reference_step_hold_sec": hold,
        "tau_u": tau_u, "plant_n_y": n, "plant_n_u": n,
        "preg_blackbox_enabled": False, "r_preg": 1.0,
        "Tau_1": max(dt, 5.0*dt), "Tau_2": max(2.0*dt, 10.0*dt), "tau_d": tau_u,
        "plant_training_method": "batch", "plant_batch_r_0": 1.0e-4,
        "plant_qnu_batch_r_0": 1.0e-2, "ctrl_learning": "NGD",
        "ctrl_epochs": 8, "mu_v": 0.005, "mu_r_0": 0.0005,
        "ctrl_qnu_learning": "NGD", "ctrl_qnu_epochs": 8,
        "mu_v_qnu": 0.005, "mu_r_0_qnu": 0.0002,
    }

MODEL_RECOMMENDED_PRESETS.update({
    "network_router_fluid_queue": _cross_domain_preset(0.005, 0.05, 80.0, 2.0, 0.15),
    "cloud_server_workload": _cross_domain_preset(0.02, 0.2, 160.0, 5.0, 0.8),
    "cpu_thermal_fan": _cross_domain_preset(0.05, 0.5, 300.0, 12.0, 2.0, 7),
    "wireless_power_snr": _cross_domain_preset(0.002, 0.02, 40.0, 0.8, 0.08),
    "accelerator_rf_cavity_amplitude": _cross_domain_preset(0.00005, 0.0005, 0.8, 0.02, 0.002),
    "accelerator_beam_position": _cross_domain_preset(0.0002, 0.002, 8.0, 0.08, 0.008),
    "microgrid_frequency_linear": _cross_domain_preset(0.002, 0.02, 40.0, 1.0, 0.08),
    "microgrid_frequency_bess_nonlinear": _cross_domain_preset(0.002, 0.02, 60.0, 1.5, 0.08, 7),
    "soil_moisture_respiration": _cross_domain_preset(0.05, 0.5, 300.0, 10.0, 2.0, 7),
    "soil_microbe_carbon_respiration": _cross_domain_preset(0.05, 0.5, 300.0, 10.0, 2.0, 7),
    "soil_carbon_priming": _cross_domain_preset(0.05, 0.5, 360.0, 12.0, 2.5, 8),
    "soil_nitrogen_n2o": _cross_domain_preset(0.02, 0.2, 180.0, 6.0, 1.0, 7),
    "soil_denitrification_aeration": _cross_domain_preset(0.02, 0.2, 180.0, 6.0, 1.0, 7),
    "soil_microbe_cn_stoichiometry": _cross_domain_preset(0.05, 0.5, 300.0, 10.0, 2.0, 8),
    "mechanical_tuned_mass_damper": _cross_domain_preset(0.0005, 0.005, 25.0, 0.25, 0.02, 8),
    "voice_coil_servo": _cross_domain_preset(0.0001, 0.001, 8.0, 0.05, 0.004, 8),
    "overhead_crane_payload_sway": _cross_domain_preset(0.001, 0.01, 40.0, 0.5, 0.04, 9),
})

MODEL_IO_RANGES = {'quadrotor_roll': {'u_min': -2.0, 'u_max': 2.0, 'd_min': -0.8, 'd_max': 0.8},
 'quadrotor_altitude': {'u_min': -2.0, 'u_max': 2.0, 'd_min': -2.0, 'd_max': 2.0},
 'two_mass_actuator_grounded_m2_linear_viscous': {'u_min': -10.0, 'u_max': 10.0, 'd_min': -10.0, 'd_max': 10.0},
 'two_mass_actuator_grounded_m2_lugre': {'u_min': -10.0, 'u_max': 10.0, 'd_min': -10.0, 'd_max': 10.0},
 'bioreactor_dissolved_oxygen': {'u_min': -2.0, 'u_max': 2.0, 'd_min': -0.15, 'd_max': 0.15},
 'photobioreactor_ph_co2': {'u_min': -2.0, 'u_max': 2.0, 'd_min': -0.35, 'd_max': 0.35},
 'chemostat_monod_biomass': {'u_min': -2.0, 'u_max': 2.0, 'd_min': -0.2, 'd_max': 0.2},
 'drug_infusion_pk': {'u_min': -2.0, 'u_max': 2.0, 'd_min': -0.35, 'd_max': 0.35},
 'drug_infusion_pkpd': {'u_min': -2.0, 'u_max': 2.0, 'd_min': -0.25, 'd_max': 0.25},
 'glucose_insulin_bergman': {'u_min': -2.0, 'u_max': 2.0, 'd_min': -1.0, 'd_max': 1.0},
 'peltier_thermal_asymmetric': {'u_min': -1.5, 'u_max': 1.5, 'd_min': -3.0, 'd_max': 5.0},
 'bidirectional_tank_level': {'u_min': -1.5, 'u_max': 1.5, 'd_min': -0.45, 'd_max': 0.65}}


MODEL_IO_RANGES.update({
    "network_router_fluid_queue": {"u_min": -1.5, "u_max": 1.5, "d_min": -3.0, "d_max": 6.0},
    "cloud_server_workload": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.8, "d_max": 1.5},
    "cpu_thermal_fan": {"u_min": -1.5, "u_max": 1.5, "d_min": -8.0, "d_max": 8.0},
    "wireless_power_snr": {"u_min": -1.5, "u_max": 1.5, "d_min": -2.5, "d_max": 2.5},
    "accelerator_rf_cavity_amplitude": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.45, "d_max": 0.45},
    "accelerator_beam_position": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.03, "d_max": 0.03},
    "microgrid_frequency_linear": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.20, "d_max": 0.20},
    "microgrid_frequency_bess_nonlinear": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.20, "d_max": 0.20},
    "soil_moisture_respiration": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.020, "d_max": 0.020},
    "soil_microbe_carbon_respiration": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.025, "d_max": 0.025},
    "soil_carbon_priming": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.025, "d_max": 0.025},
    "soil_nitrogen_n2o": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.015, "d_max": 0.015},
    "soil_denitrification_aeration": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.015, "d_max": 0.015},
    "soil_microbe_cn_stoichiometry": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.025, "d_max": 0.025},
    "mechanical_tuned_mass_damper": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.20, "d_max": 0.20},
    "voice_coil_servo": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.025, "d_max": 0.025},
    "overhead_crane_payload_sway": {"u_min": -1.5, "u_max": 1.5, "d_min": -0.90, "d_max": 0.90},
})


# Presets and ranges for delayed-input plant variants.
_DELAY_PRESET_BASES = {
    "network_router_fluid_queue_with_delay": "network_router_fluid_queue",
    "network_router_fluid_queue_with_large_delay": "network_router_fluid_queue",
    "cloud_server_workload_with_delay": "cloud_server_workload",
    "microgrid_frequency_bess_nonlinear_with_delay": "microgrid_frequency_bess_nonlinear",
    "soil_moisture_respiration_with_delay": "soil_moisture_respiration",
    "soil_carbon_priming_with_delay": "soil_carbon_priming",
    "accelerator_rf_cavity_amplitude_with_delay": "accelerator_rf_cavity_amplitude",
    "overhead_crane_payload_sway_with_delay": "overhead_crane_payload_sway",
}
for _name, _base in _DELAY_PRESET_BASES.items():
    _p = dict(MODEL_RECOMMENDED_PRESETS[_base])
    _p["plant_n_u"] = max(8, int(_p.get("plant_n_u", 6)) + 3)
    _p["plant_n_y"] = max(8, int(_p.get("plant_n_y", 6)) + 2)
    _p["step_hold_sec"] = max(float(_p["step_hold_sec"]), 4.0 * float(_p["dt"]))
    _p["reference_step_hold_sec"] = _p["step_hold_sec"]
    MODEL_RECOMMENDED_PRESETS[_name] = _p
    MODEL_IO_RANGES[_name] = dict(MODEL_IO_RANGES[_base])


MODEL_IO_RANGES["two_mass_actuator_grounded_m2_lugre2"] = dict(
    MODEL_IO_RANGES["two_mass_actuator_grounded_m2_lugre"]
)

def recommended_preset(model_name):
    preset = MODEL_RECOMMENDED_PRESETS.get(str(model_name))
    if preset is None:
        return None
    result = dict(preset)
    result.update(MODEL_IO_RANGES.get(str(model_name), {}))
    return result
